### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SonaliBendre** [vinodnimbalkar/mxplayer#1]
[file] Cannot open file '': Invalid argument
Failed to open .

Exiting... (Errors when loading file)

**Comment by vinodnimbalkar** [comment]
Hi @SonaliBendre 
Please provide the URL link which you are trying to play, so I'll test.

**Comment by SonaliBendre** [comment]
https://www.mxplayer.in/live-tv/lock-upp-live-live-channel-8090lockupin

**Comment by vinodnimbalkar** [comment]
@SonaliBendre script updated, now it will play mxplayer live-tv link also.

**Comment by SonaliBendre** [comment]
thank you ver much

**Comment by SonaliBendre** [comment]
BTW which distro sir?

**Comment by SonaliBendre** [comment]
just saw your dotfiles repository. do you still use ubuntu?
when i was learning unix I got ubuntu tutorials mostly so I used ubuntu mostly but now after trying arch life is very easy+automated and its saves time. APT is horrible

**Comment by SonaliBendre** [comment]
BTW doesn't mpv already support mxplayer links already? just the live tv urls don't work

**Comment by SonaliBendre** [comment]
> @SonaliBendre script updated, now it will play mxplayer live-tv link also.

only https://www.mxplayer.in/live-tv/lock-upp-live-live-channel-8090lockupin video is playing. can you add all live tv links?

**Comment by vinodnimbalkar** [comment]
> only https://www.mxplayer.in/live-tv/lock-upp-live-live-channel-8090lockupin video is playing. can you add all live tv links?

Yes, I'll add support to all live tv links, whenever I'll get time. @SonaliBendre
till then you can use this script [livechannel](https://gist.github.com/vinodnimbalkar/3ad175badbd8f9141e476493dec5fe61), It has **rofi** support but if required you can do changes in it according to you for **dmenu** or **fzf**
